---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sample
  namespace: local
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: sample
  chart:
    git: git@github.com:ovrdoz/gitops-with-fluxcd
    ref: master
    path: charts/sample